<?php

namespace common\models\helpers;

use common\models\User;
use yii\helpers\Url;

class UserGenerator
{
    public static function gen()
    {
        ini_set("max_execution_time", "600");
        $zoomerUsers = [
            ['login' => 'ТикТок_Король', 'password' => 'Dance4Views!'],
            ['login' => 'Мемный_Магистр', 'password' => 'DankM3m3s'],
            ['login' => 'Дроп_Изи_Деньги', 'password' => 'FlexOnHaters'],
            ['login' => 'Бумер_В_ТикТоке', 'password' => 'OldButCool'],
            ['login' => 'Кринж_И_Плач', 'password' => 'Facepalm2024'],
            ['login' => 'Чилю_С_Кофе', 'password' => 'NoStressBro'],
            ['login' => 'Аниме_Слизь', 'password' => 'Waifu4Ever'],
            ['login' => 'Гугл_Мой_Папа', 'password' => 'SearchItUp'],
            ['login' => 'Спать_Не_Надо', 'password' => '5amClub'],
            ['login' => 'Рофлю_До_Слез', 'password' => 'LmaoDead'],
            ['login' => 'Дискорд_Отец', 'password' => 'VoiceChatGod'],
            ['login' => 'Пранкер_Легенда', 'password' => 'FooledYa'],
            ['login' => 'Шаверма_Босс', 'password' => 'KebabKing'],
            ['login' => 'Кибер_Деревенщина', 'password' => 'NoWiFiLife'],
            ['login' => 'ОК_Бумер_Пока', 'password' => 'GenZrulez'],
            ['login' => 'Лайки_Или_Бан', 'password' => 'CloutChaser'],
            ['login' => 'Задрот_С_Душой', 'password' => 'NerdButCool'],
            ['login' => 'Кофе_Или_Смерть', 'password' => 'CaffeineFix'],
            ['login' => 'Дедлайн_Близко', 'password' => 'PanicTime'],
            ['login' => 'Флекс_На_Миллион', 'password' => 'RichAesthetic'],
            ['login' => 'Вайб_И_Точка', 'password' => 'ChillVibesOnly'],
            ['login' => 'Ютуб_Зависимый', 'password' => 'SkipAdsNow'],
            ['login' => 'Твич_Донатер', 'password' => 'Bits4Life'],
            ['login' => 'Инста_Фейк', 'password' => 'FakeFilterz'],
            ['login' => 'Реддит_Троль', 'password' => 'DownvoteMe'],
            ['login' => 'Телеграм_Анон', 'password' => 'SecretChat'],
            ['login' => 'Фейсбук_Динозавр', 'password' => 'ZuckIsWatching'],
            ['login' => 'Пинтерест_Дизайнер', 'password' => 'PinterestPro'],
            ['login' => 'Тумблр_Поэт', 'password' => 'DeepAndDark'],
            ['login' => 'Вайбер_Мертвец', 'password' => 'RIPMessages'],
            ['login' => 'Снапчат_Призрак', 'password' => 'GhostSnap'],
            ['login' => 'Гугл_Футурист', 'password' => 'AIisComing'],
            ['login' => 'Мем_Деспот', 'password' => 'MemeOverlord'],
            ['login' => 'Дота_Профи', 'password' => 'GGmidOrFeed'],
            ['login' => 'Форнаит_Нуб', 'password' => 'NoobBuilder'],
            ['login' => 'Майн_Ностальгист', 'password' => 'DiamondMiner'],
            ['login' => 'Киберпанк_Мечтатель', 'password' => 'NeonDreams'],
            ['login' => 'Хакер_Чайник', 'password' => 'HelloWorld123'],
            ['login' => 'ВПН_Любитель', 'password' => 'HideMyIP'],
            ['login' => 'Тор_Бро', 'password' => 'DarkWebSurf'],
            ['login' => 'Крипто_Энтузиаст', 'password' => 'ToTheMoon'],
            ['login' => 'НФТ_Художник', 'password' => 'PixelArtKing'],
            ['login' => 'Метавселенная_Пионер', 'password' => 'VRisFuture'],
            ['login' => 'ИИ_Параноик', 'password' => 'SkynetIsNear'],
            ['login' => 'Робот_Сопротивленец', 'password' => 'NoAIcontrol'],
            ['login' => 'Тесла_Фанат', 'password' => 'ElonMuskFan'],
            ['login' => 'Космос_Мечтатель', 'password' => 'MarsOrBust'],
            ['login' => 'ЗОЖ_Тиран', 'password' => 'VeganGains'],
            ['login' => 'Спортзал_Крыса', 'password' => 'LiftHeavyBro'],
            ['login' => 'Кофе_Наркоман', 'password' => 'EspressoShot'],
            ['login' => 'Энергетик_Зависимый', 'password' => 'RedBullFly'],
            ['login' => 'Фастфуд_Гурман', 'password' => 'BurgerLover'],
            ['login' => 'Веган_Агрессор', 'password' => 'MeatIsMurder'],
            ['login' => 'Шаурма_Фанат', 'password' => 'Doner4Life'],
            ['login' => 'Пицца_Культист', 'password' => 'PineappleNo'],
            ['login' => 'Суши_Мастер', 'password' => 'WasabiBurn'],
            ['login' => 'Кулинар_Троль', 'password' => 'SaltBaeWannabe'],
            ['login' => 'Диета_Срыв', 'password' => 'CheatDayEveryday'],
            ['login' => 'Геймер_Ночник', 'password' => 'NoSleepGamer'],
            ['login' => 'Стример_Начинающий', 'password' => 'FirstStream'],
            ['login' => 'Киберспорт_Мечта', 'password' => 'ProGamerWannabe'],
            ['login' => 'Консоль_Фанат', 'password' => 'PS5orDie'],
            ['login' => 'ПК_Мастер', 'password' => 'RGB4Life'],
            ['login' => 'Ретро_Геймер', 'password' => 'NESforever'],
            ['login' => 'Мод_Творец', 'password' => 'SkyrimBelongsToMods'],
            ['login' => 'Сервер_Админ', 'password' => 'RootAccess'],
            ['login' => 'Баги_Любитель', 'password' => 'FeatureNotBug'],
            ['login' => 'Код_Криворукий', 'password' => 'HelloWorldError'],
            ['login' => 'Гит_Террорист', 'password' => 'ForcePushAll'],
            ['login' => 'Старый_Железный', 'password' => 'WinXPNostalgia'],
            ['login' => 'Новый_Технофил', 'password' => 'LatestGadget'],
            ['login' => 'Гаджет_Зависимый', 'password' => 'BuyItAll'],
            ['login' => 'Эпл_Фанат', 'password' => 'IPhone20User'],
            ['login' => 'Андроид_Гуру', 'password' => 'CustomROMs'],
            ['login' => 'Линукс_Гик', 'password' => 'SudoOrDie'],
            ['login' => 'Винда_Страдалец', 'password' => 'BlueScreenLife'],
            ['login' => 'Мак_Сноб', 'password' => 'OverpricedFan'],
            ['login' => 'Пират_СтаройШколы', 'password' => 'TorrentKing'],
            ['login' => 'Фильмы_Пират', 'password' => 'YTSFanClub'],
            ['login' => 'Музыка_Вор', 'password' => 'MP3Collector'],
            ['login' => 'Софт_Кракер', 'password' => 'PatchMeIfYouCan'],
            ['login' => 'Книги_Пират', 'password' => 'PDFLibrary'],
            ['login' => 'Мемы_Вор', 'password' => 'RepostMachine'],
            ['login' => 'Контент_Копирайтер', 'password' => 'RewriteKing'],
            ['login' => 'Оригинал_Призрак', 'password' => 'UniqueSnowflake'],
            ['login' => 'Креатив_Ноль', 'password' => 'CtrlCVExpert'],
            ['login' => 'Вдохновение_Умерло', 'password' => 'NoNewIdeas'],
            ['login' => 'Прокрастинатор_Профи', 'password' => 'TomorrowTask'],
            ['login' => 'Дедлайн_Бегун', 'password' => 'LastMinuteWork'],
            ['login' => 'Овертайм_Любитель', 'password' => 'NoLifeOnlyWork'],
            ['login' => 'Фриланс_Мечта', 'password' => 'NoOfficeFreedom'],
            ['login' => 'Офис_Ненавистник', 'password' => 'RemoteWork4Life'],
            ['login' => 'Зарплата_Мечты', 'password' => 'RichQuick'],
            ['login' => 'Босс_Тиранин', 'password' => 'MyWayOrHighway'],
            ['login' => 'Коллега_Демон', 'password' => 'CoffeeThief'],
            ['login' => 'Карьера_Крушение', 'password' => 'PromotionNever'],
            ['login' => 'Увольнение_Мечта', 'password' => 'FireMePlease'],
            ['login' => 'Пенсия_Далеко', 'password' => 'WorkTillDeath'],
            ['login' => 'Надежда_Умерла', 'password' => 'NoFutureLeft'],
            ['login' => 'Оптимизм_Потерян', 'password' => 'CynicalView'],
            ['login' => 'Самоирония_Король', 'password' => 'LaughAtMyself'],
            ['login' => 'Депрессия_Друг', 'password' => 'DarkThoughts'],
            ['login' => 'Тревога_Подруга', 'password' => 'PanicAttack'],
            ['login' => 'Прокрастинация_Босс', 'password' => 'DoItLater'],
            ['login' => 'Мотивация_Призрак', 'password' => 'GoneForever'],
            ['login' => 'Дисциплина_Шутка', 'password' => 'NeverAgain'],
            ['login' => 'Привычки_Плохие', 'password' => 'BadHabitsWin'],
            ['login' => 'ЗОЖ_Неудачник', 'password' => 'GymNeverAgain'],
            ['login' => 'Диета_Провал', 'password' => 'CheatDayEveryday1'],
            ['login' => 'Спорт_Враги', 'password' => 'CouchPotato'],
            ['login' => 'Здоровье_Шутка', 'password' => 'DoctorWho'],
            ['login' => 'Врач_Страх', 'password' => 'NoCheckup'],
            ['login' => 'Аптека_Друг', 'password' => 'PillPop'],
            ['login' => 'Боль_Постоянная', 'password' => 'ChronicPain'],
            ['login' => 'Возраст_Проблема', 'password' => 'OldButYoung'],
            ['login' => 'Молодость_Ушла', 'password' => 'TeenNoMore'],
            ['login' => 'Взросление_Боль', 'password' => 'BillsBillsBills'],
            ['login' => 'Ответственность_Страх', 'password' => 'NoAdulting'],
            ['login' => 'Долги_Гора', 'password' => 'InDebtAgain'],
            ['login' => 'Кредиты_Кошмар', 'password' => 'BankOwnsMe'],
            ['login' => 'Ипотека_Тюрьма', 'password' => '30YearsSlave'],
            ['login' => 'Накопления_Миф', 'password' => 'LiveForToday'],
            ['login' => 'Инвестиции_Мечта', 'password' => 'LamboSoon'],
            ['login' => 'Крипто_Надежда', 'password' => 'HODLgang'],
            ['login' => 'Биткоин_Спаситель', 'password' => 'ToTheMoon1'],
            ['login' => 'Акции_Игра', 'password' => 'WallStreetBets'],
            ['login' => 'Риск_Жизнь', 'password' => 'YOLOinvest'],
            ['login' => 'Богатство_Фантазия', 'password' => 'DreamBig'],
            ['login' => 'Бедность_Реальность', 'password' => 'RamenDiet'],
            ['login' => 'Минималка_Судьба', 'password' => 'SurvivalMode'],
            ['login' => 'Работа_Ненависть', 'password' => 'TGIFeveryday'],
            ['login' => 'Карьера_Тупик', 'password' => 'NoPromotion'],
            ['login' => 'Мечты_Разбиты', 'password' => 'RealityCheck'],
            ['login' => 'Будущее_Туман', 'password' => 'NoCrystalBall'],

        ];

        foreach ($zoomerUsers as $user) {
            $model = new User();
            $model->username = $user['login'];
            $model->email = $user['password']. '@example.com';
            $model->setPassword($user['password']);
            $model->generateAuthKey();
            $model->save();
        }

        echo 'Юзеры сгенерированы';
    }
}