<?php

namespace frontend\controllers;

use common\models\Answers;
use common\models\City;
use common\models\Games;
use common\models\GameToUser;
use common\models\helpers\Session;
use common\models\LineGameStats;
use common\models\QuestGameTour;
use common\models\QuestGameToUser;
use common\models\Questions;
use common\models\StormGameStats;
use common\models\StormGameToUser;
use common\models\Tours;
use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Symfony\Component\Console\Question\Question;
use Yii;
use yii\base\InvalidArgumentException;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\web\NotFoundHttpException;

/**
 * Site controller
 */
class SiteController extends Controller
{

    public function init()
    {
        $this->enableCsrfValidation = false;
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = 'adaptive';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout', 'signup', 'about', 'index'],
                'rules' => [
                    [
                        'actions' => ['signup', 'index'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'about', 'question'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
//            'verbs' => [
//                'class' => VerbFilter::class,
//                'actions' => [
//                    'logout' => ['post'],
//                ],
//            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => \yii\web\ErrorAction::class,
            ],
            'captcha' => [
                'class' => \yii\captcha\CaptchaAction::class,
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout = false;
        if ($gameId = Session::getByKey(Session::CURRENT_GAME_ID)) {

            if ($g = StormGameToUser::find()->where(['id' => $gameId, 'user_id' => Yii::$app->user->id])->andWhere(['is', 'end_at', new \yii\db\Expression('null')])->one()) {
                $tour = StormGameStats::switchTour();
                $this->redirect('/frontend/web/storm/tour?id=' . $tour);
            } else {
                $tour = QuestGameTour::find()->where(['game_id' => Session::getByKey(Session::CURRENT_GAME_ID)])->orderBy('tour_id DESC')->one();
                if ($tour) {
                    if ($tour->end_at == null) {
                        $this->redirect('/frontend/web/quest/tour?id=' . $tour->tour_id);
                    }
                    $game = QuestGameToUser::getRealGameId($tour->game_id);
                    if ($game) {
                    $lastTourGame = Tours::find()->where(['game_id' => $game->game_id])->orderBy('id ASC')->all();
                    if ($lastTourGame) {
                        $i = 0;
                        foreach ($lastTourGame as $tourGame) {
                            if ($i == 1) {
                                $this->redirect('/frontend/web/quest/new-tour?id=' . $tourGame->id);
                            }
                            if ($tourGame->id == $tour->tour_id) {
                                $i = 1;
                            }
                        }
                    }
                }
                    $i = 0;
                }
            }

        }


        $city = City::find()->all();
        return $this->render('landing-pip', ['city' => $city]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        $this->layout = false;
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        if (isset($_SERVER['HTTP_REFERER'])) {
            $_SESSION['url_for_signup'] = $_SERVER['HTTP_REFERER'];
        }
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';

        return $this->render('login-pip', [
            'model' => $model,
        ]);
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        }

        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * @param $id
     * @return void
     * @throws NotFoundHttpException
     */
    public function actionQuestion($id): string
    {

        $question = Questions::findOne($id);

        if (!$question) {
            throw new NotFoundHttpException('The requested question does not exist.');
        }

        $attachments = $question->getQuestionsAttachments()->all();

        return $this->render('question', ['question' => $question, 'attachments' => $attachments]);
    }

    public function actionNextQuestion()
    {
        if (empty($_POST['id']) || empty($_POST['tour_id'])) {
            $response['success'] = false;
            $response['msg'] = 'Произошла ошибка, обратитесь к администратору';
            return json_encode($response);
        }

        Answers::checkAnswer($_POST['id'], $_POST['answer']);

        $response['success'] = true;

        if ($nextQuestion = Questions::getNextQuestion($_POST['id'])) {
            $response['url'] = $_SERVER["HTTP_ORIGIN"] . \yii\helpers\Url::to(['/site/question', 'id' => $nextQuestion->id]);
        } else {
            $response['url'] = $_SERVER["HTTP_ORIGIN"] .  \yii\helpers\Url::to(['/site/end-tour', 'id' => $_POST['tour_id']]);
        }

        return json_encode($response);
    }

    public function actionEndTour($id): string
    {
        $tour = Tours::findOne($id);
        $stat = LineGameStats::getTourStatistic($id);

        return $this->render('endTour', ['tour' => $tour, 'stat' => $stat]);
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            if (isset($_SESSION['url_for_signup']) && $_SESSION['url_for_signup']) {
                $lForm = new LoginForm();
                $lForm->username = $model->username;
                $lForm->password = $model->password;
                if ($lForm->login()) {
                    return $this->redirect($_SESSION['url_for_signup']);
                }

            } else {
                $lForm = new LoginForm();
                $lForm->username = $model->username;
                $lForm->password = $model->password;
                if ($lForm->login()) {
                    return $this->redirect('/');
                }
            }
            return $this->goHome();
        }

        $this->layout = false;
        return $this->render('signup-pip', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            }

            Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Verify email address
     *
     * @param string $token
     * @throws BadRequestHttpException
     * @return yii\web\Response
     */
    public function actionVerifyEmail($token)
    {
        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if (($user = $model->verifyEmail()) && Yii::$app->user->login($user)) {
            Yii::$app->session->setFlash('success', 'Your email has been confirmed!');
            return $this->goHome();
        }

        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }

    /**
     * Resend verification email
     *
     * @return mixed
     */
    public function actionResendVerificationEmail()
    {
        $model = new ResendVerificationEmailForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            }
            Yii::$app->session->setFlash('error', 'Sorry, we are unable to resend verification email for the provided email address.');
        }

        return $this->render('resendVerificationEmail', [
            'model' => $model
        ]);
    }

    public function actionNewGame($id): string
    {
        $game = Games::getGameByUrl($id);

        if (!$game) {
            throw new NotFoundHttpException('Игры не существует');
        }

        return $this->render('game', ['game' => $game]);
    }

    public function actionGameStart()
    {
        $response['success'] = false;
        if (empty($_POST['id'])) {
            return json_encode($response);
        }

        $game = Games::getGameById($_POST['id']);

        if (!$game) {
            return json_encode($response);
        }

        $tour = Tours::getNextTour($game->id);

        if (!$tour) {
            return json_encode($response);
        }

        GameToUser::startGame($game->id);


        $response['success'] = true;
        $response['url'] = Url::to(['/site/tour', 'id' => $tour->id]);

        return json_encode($response);
    }

    public function actionTour($id): string
    {
        $tour = Tours::getTourById($id);

        if (!$tour) {
            throw new NotFoundHttpException('Тура не существует');
        }

        return $this->render('tour', ['tour' => $tour]);
    }

    public function actionTourStart()
    {
        $response['success'] = false;

        if (empty($_POST['id'])) {
            return json_encode($response);
        }

        $tour = Tours::getTourById($_POST['id']);

        if (!$tour) {
            return json_encode($response);
        }

        $question = Questions::getFirstQuestion($tour->id);

        if (!$question) {
            return json_encode($response);
        }

        $response['success'] = true;
        $response['url'] = Url::to(['/site/question', 'id' => $question->id]);

        return json_encode($response);
    }

    public function actionNextTour()
    {
        $response['success'] = false;

        if (empty($_POST['id'])) {
            return json_encode($response);
        }


        $startedGameId = Session::getByKey(Session::CURRENT_GAME_ID);
        $gameId = GameToUser::getOriginGameId($startedGameId);
        $tour = Tours::getNextTour($gameId, $_POST['id']);

        $response['success'] = true;
        if (!$tour) {
            $response['url'] = Url::to(['/site/end-game', 'id' => $startedGameId]);
            return json_encode($response);
        }

        $response['url'] = Url::to(['/site/tour', 'id' => $tour->id]);

        return json_encode($response);
    }

    public function actionEndGame($id): string
    {
        $toursList = [];
        $stat = LineGameStats::getGameStatistic($id);

        if ($stat) {
            $toursList = LineGameStats::getToursList($stat);
        }

        return $this->render('endGame', ['stat' => $stat, 'toursList' => $toursList]);

    }

    /**
     * Обработка успешной авторизации через VK
     */
    public function onAuthSuccess(ClientInterface $client)
    {
        $attributes = $client->getUserAttributes();

        // Логируем полученные данные для отладки
        Yii::info('VK attributes: ' . print_r($attributes, true), 'auth');

        // Получаем email из атрибутов
        $email = $attributes['email'] ?? null;
        $vkId = (string)$attributes['id'];

        // 1. Ищем пользователя по vkontakte_id
        $user = User::findByVkontakteId($vkId);

        if ($user) {
            // Обновляем данные пользователя из VK
            $user->updateFromVK($attributes);

            if (Yii::$app->user->login($user, 3600 * 24 * 30)) {
                Yii::$app->session->setFlash('success', 'Вы успешно вошли через VK!');
                return $this->goBack();
            }
        }

        // 2. Если пользователь найден по email (привязка аккаунтов)
        if ($email && !$user) {
            $user = User::findByEmail($email);

            if ($user) {
                // Спрашиваем пользователя, хочет ли он привязать VK
                Yii::$app->session->set('vk_attributes', $attributes);
                return $this->redirect(['/site/link-vk']);
            }
        }

        // 3. Регистрируем нового пользователя
        if (!$user) {
            $user = User::createFromVK($attributes);

            if ($user->save()) {
                if (Yii::$app->user->login($user, 3600 * 24 * 30)) {
                    Yii::$app->session->setFlash('success', 'Регистрация через VK прошла успешно!');
                    return $this->goBack();
                }
            } else {
                Yii::$app->session->setFlash('error',
                    'Ошибка при сохранении пользователя: ' .
                    print_r($user->errors, true)
                );
            }
        }

        return $this->goHome();
    }

    /**
     * Страница для привязки VK к существующему аккаунту
     */
    public function actionLinkVk()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['/site/login']);
        }

        $attributes = Yii::$app->session->get('vk_attributes');

        if (!$attributes) {
            return $this->redirect(['/site/login']);
        }

        $user = Yii::$app->user->identity;

        if (Yii::$app->request->isPost) {
            if (Yii::$app->request->post('confirm') === 'yes') {
                // Привязываем VK к аккаунту
                $user->vkontakte_id = (string)$attributes['id'];
                $user->vkontakte_data = json_encode($attributes);
                $user->updated_at = time();

                if ($user->save()) {
                    Yii::$app->session->remove('vk_attributes');
                    Yii::$app->session->setFlash('success', 'Аккаунт VK успешно привязан!');
                    return $this->goHome();
                }
            } else {
                Yii::$app->session->remove('vk_attributes');
                return $this->goHome();
            }
        }

        return $this->render('link-vk', [
            'vkName' => $attributes['first_name'] . ' ' . $attributes['last_name'],
        ]);
    }

    /**
     * Обработка отмены авторизации
     */
    public function onAuthCancel()
    {
        Yii::$app->session->setFlash('warning', 'Авторизация через VK была отменена.');
        return $this->redirect(['/site/login']);
    }

    public function actionChangeCity()
    {
        $response['success'] = false;

        if (!isset($_POST['id']) or empty($_POST['id'])) {
            return json_encode($response);
        }

        $city = City::find()->where(['id' => $_POST['id']])->one();

        if (!$city) {
            return json_encode($response);
        }

        $games = $city->getGames()->where(['public' => true])->all();

        $response['success'] = true;
        $response['content'] = $this->renderPartial('part/games', ['games' => $games]);
        return json_encode($response);
    }

    public function actionGameDetail($id)
    {
        $game = Games::findOne($id);

        if (!$game) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

        $this->layout = false;
        return $this->render('game-detail-pip', ['game' => $game]);
    }
}
